#version: '3.8'

services:
  db:
    image: postgres:15
    container_name: manumarket_db
    restart: always
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       manumarket
    volumes:
      - manumarket-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - manumarket-network  # Conectando db a la red


  ventas_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ventas_api
    restart: always
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - bus  # Asegurando que el backend dependa del BUS
    env_file:
      - .env
    networks:
      - manumarket-network  # Asegurarse de que esté en la misma red

  frontend_node:
    image: node:18-alpine
    container_name: frontend_node
    restart: always
    working_dir: /app
    volumes:
      - ./frontend-node:/app
    command: sh -c "npm install && npx nodemon --watch src --exec 'node src/server.js'"
    ports:
      - "3000:3000"
    depends_on:
      - ventas_api
    networks:
      - manumarket-network  

  bus:
    image: jrgiadach/soabus
    container_name: soabus
    ports:
      - "5000:5000"  # Puerto del BUS
    environment:
      - SOME_ENV_VAR=value  # Si el BUS necesita alguna variable de entorno
    restart: always
    networks:
      - manumarket-network

  auth_service:
    build:
      context: .  # Usar el Dockerfile de la raíz
      dockerfile: Dockerfile  # Especifica que use el Dockerfile de la raíz
    container_name: auth_service
    restart: always
    volumes:
      - ./backend:/app  # Esto monta la carpeta backend que incluye auth_service y ventas
    ports:
      - "8001:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - manumarket-network  # Asegurarse de que esté en la misma red

volumes:
  manumarket-data:

networks:
  manumarket-network:
    driver: bridge